### ISSUE TITLE
Versioning issue

### ISSUE THREAD

**Issue by IzzySoft** [0xAdiyat/ToDo-WishFlow#1]
Looks like the APKs of all your releases identify as the very same version:

    package: name='com.example.todo_wishflow' versionCode='1' versionName='1.0.0'

(taken from the v1.0.2 tag). That not only makes it hard to tell them apart, but also difficult to update – as Android will consider all of them being the same version, and thus not suggest to update.

To fix that, [here's the place](https://github.com/0xAdiyat/ToDo-WishFlow/blob/master/pubspec.yaml#L18) to adjust: Please bring `versionName` (the part before the `+` symbol) in sync with your tag names, and make sure to always increase `versionCode` (the part following the `+`) when making a new release.

Btw: the `com.example.` prefix is only intended for testing and demonstrations. So with that package name your app would be rejected at PlayStore, should you ever aim to publish there.

**Comment by 0xAdiyat** [comment]
> Looks like the APKs of all your releases identify as the very same version:
> 
> ```
> package: name='com.example.todo_wishflow' versionCode='1' versionName='1.0.0'
> ```
> 
> (taken from the v1.0.2 tag). That not only makes it hard to tell them apart, but also difficult to update – as Android will consider all of them being the same version, and thus not suggest to update.
> 
> To fix that, [here's the place](https://github.com/0xAdiyat/ToDo-WishFlow/blob/master/pubspec.yaml#L18) to adjust: Please bring `versionName` (the part before the `+` symbol) in sync with your tag names, and make sure to always increase `versionCode` (the part following the `+`) when making a new release.
> 
> Btw: the `com.example.` prefix is only intended for testing and demonstrations. So with that package name your app would be rejected at PlayStore, should you ever aim to publish there.

Hey @IzzySoft, thanks for flagging this! Really appreciate your input. I see what you mean about the versioning issue and the package name. I'll get on it and make sure to sync up the versionName and versionCode for better differentiation. Also, good catch on the package name. Just to give you a heads-up, this was actually a practice project from way back when I started learning Flutter. It's kind of a side thing, which is why there's an 'example' in the package name. I didn't invest as much time in it since it's not intended for Play Store release. Still, your feedback is super helpful for cleaning things up and learning along the way. Thanks for helping me improve the app.

Cheers!

**Comment by 0xAdiyat** [comment]
I have resolved the issue. If you come across anything else, feel free to let me know. Closing this issue now. Thanks again!

**Comment by IzzySoft** [comment]
> I have resolved the issue.

Partially. You forgot to increase `versionCode` – and the package name is still in the `com.example` domain. I've no problem with the latter, and the former is fine if fixed with the next release – but looking around I also did not find any license declared. Did you decide for any already?

**Comment by 0xAdiyat** [comment]
> > I have resolved the issue.
> 
> Partially. You forgot to increase `versionCode` – and the package name is still in the `com.example` domain. I've no problem with the latter, and the former is fine if fixed with the next release – but looking around I also did not find any license declared. Did you decide for any already?

No, I haven't decided yet. But now am thinking of going for MIT license. What do you think?

**Comment by IzzySoft** [comment]
Sounds good to me! The [list of potential licenses](https://spdx.org/licenses/) (those approved by OSI/FSF) is quite long, I cannot remember them all. MIT is a light-weight one and easy to understand (like the BSD licenses), in the section of the rather permissive licenses. On the other end of the spectrum would be GPL/AGPL, often called "copy-left" (for some background on the latter, see e.g. [Google Hates the AGPL? Not Surprising](http://www.russellbeattie.com/blog/google-hates-the-agpl-not-surprising)).

In your case, I think MIT is a good choice. So would the others – but as I wrote, what I like about MIT and BSD is that the terms fit on less than half a letter page and do not require half-a-day study :smile:

**Comment by 0xAdiyat** [comment]
> Sounds good to me! The [list of potential licenses](https://spdx.org/licenses/) (those approved by OSI/FSF) is quite long, I cannot remember them all. MIT is a light-weight one and easy to understand (like the BSD licenses), in the section of the rather permissive licenses. On the other end of the spectrum would be GPL/AGPL, often called "copy-left" (for some background on the latter, see e.g. [Google Hates the AGPL? Not Surprising](http://www.russellbeattie.com/blog/google-hates-the-agpl-not-surprising)).
> 
> In your case, I think MIT is a good choice. So would the others – but as I wrote, what I like about MIT and BSD is that the terms fit on less than half a letter page and do not require half-a-day study :smile:

True, true :D MIT License is indeed simple and easy to understand, which aligns well with the project's goals. I appreciate your thoughts on the matter, Sir @IzzySoft

**Comment by IzzySoft** [comment]
Thanks! :heart_eyes: I see the license is applied already.

Are you going to keep the `com.example.*` – or is that going to be replaced by a "real one" as well? Asking because the latter would require those already using your app to uninstall and re-install it (no direct update possible, as a different `applicationId` means it's a different app), losing all data on the way (unless there's an export/import feature) – so if that should be done, it better be done as early as possible (so it affects as few people as possible).

**Comment by 0xAdiyat** [comment]
> Thanks! :heart_eyes: I see the license is applied already.
> 
> Are you going to keep the `com.example.*` – or is that going to be replaced by a "real one" as well? Asking because the latter would require those already using your app to uninstall and re-install it (no direct update possible, as a different `applicationId` means it's a different app), losing all data on the way (unless there's an export/import feature) – so if that should be done, it better be done as early as possible (so it affects as few people as possible).


You're right, there's a lot of room for improvement and innovation in the realm of ToDo apps. Back when I was learning, I created this app as a learning experience, and while it's been a valuable journey, I don't think this app has that many users tbh. As its sole purpose was showcasing my work/journey keeping it a open source project. While I don't have immediate plans for further work on this app, your feedback is definitely noted will be of great help for my future projects too. If I do decide to revisit it or create something new, I'll keep your suggestions in mind. Thanks again for your thoughtful input!😄

**Comment by IzzySoft** [comment]
Gladly! I'd add your app to [my F-Droid repository](https://apt.izzysoft.de/fdroid) if you'd like. That is, if you want to keep up development and have your app made known to a broader audience. All conditions were met the moment you added the license, so the package name (at least for my repo) would just be a formality we can also skip. Just if you'd decide to bring it into Google's walled garden, you'd be required to change the `applicationId` – which is why I suggested to better do that early.

If you want to stick to the current package name, all I'd need is an "OK" from you and your app can go live within 24h (future updates would then be pulled within 24h of your making them available as well, automatically – so those using my repo can not only install your app from there, but would also receive updates automatically). So just let me know then :smiley:

However you decide: all the best for you and your further development!

**Comment by 0xAdiyat** [comment]
> Gladly! I'd add your app to [my F-Droid repository](https://apt.izzysoft.de/fdroid) if you'd like. That is, if you want to keep up development and have your app made known to a broader audience. All conditions were met the moment you added the license, so the package name (at least for my repo) would just be a formality we can also skip. Just if you'd decide to bring it into Google's walled garden, you'd be required to change the `applicationId` – which is why I suggested to better do that early.
> 
> If you want to stick to the current package name, all I'd need is an "OK" from you and your app can go live within 24h (future updates would then be pulled within 24h of your making them available as well, automatically – so those using my repo can not only install your app from there, but would also receive updates automatically). So just let me know then :smiley:
> 
> However you decide: all the best for you and your further development!

Ohoo sounds great. You should have told me earlier. Ok ok then i will change the application id afterwards you can add it as u please.

**Comment by 0xAdiyat** [comment]
> Gladly! I'd add your app to [my F-Droid repository](https://apt.izzysoft.de/fdroid) if you'd like. That is, if you want to keep up development and have your app made known to a broader audience. All conditions were met the moment you added the license, so the package name (at least for my repo) would just be a formality we can also skip. Just if you'd decide to bring it into Google's walled garden, you'd be required to change the `applicationId` – which is why I suggested to better do that early.
> 
> If you want to stick to the current package name, all I'd need is an "OK" from you and your app can go live within 24h (future updates would then be pulled within 24h of your making them available as well, automatically – so those using my repo can not only install your app from there, but would also receive updates automatically). So just let me know then 😃
> 
> However you decide: all the best for you and your further development!

Hey @IzzySoft brother I have updated the package name and here goes my thumbs for yaa <'3

**Comment by IzzySoft** [comment]
Yay! And there you go: your app should [show up here](https://apt.izzysoft.de/packages/com.anon007.todo_wishflow/) around 6 pm UTC (the next repo sync) then. Welcome aboard! And welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme once you've verified.

Should you have additional screenshots that should be included, just let me know. I can also send you a PR with the metadata I've set up in Fastlane format, so (maybe with the help of my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688)) you can control how your app is being presented :wink:

**Comment by 0xAdiyat** [comment]
> Yay! And there you go: your app should [show up here](https://apt.izzysoft.de/packages/com.anon007.todo_wishflow/) around 6 pm UTC (the next repo sync) then. Welcome aboard! And welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme once you've verified.
> 
> Should you have additional screenshots that should be included, just let me know. I can also send you a PR with the metadata I've set up in Fastlane format, so (maybe with the help of my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688)) you can control how your app is being presented :wink:



Been waiting to see it go live. I have also updated the readme with IzzyOnDroid badge 📛

**Comment by IzzySoft** [comment]
Thanks! And yes, live now since about 90 minutes :smiley:
