### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by IzzySoft** [0xAdiyat/ToDo-WishFlow#5]
A scan ([see here](https://gitlab.com/IzzyOnDroid/repo/-/issues/477) for details and background) just revealed the APKs at your releases are signed using an expired debug key ("denyAfter 2019-01-01"). As that has security implications, may I ask you to please switch to a proper release key, and provide the corresponding APK signed with it (as you upload your app to Google Play which does not accept it if signed with a debug key, you certainly must have a proper one)? Thanks in advance!

**Comment by IzzySoft** [comment]
@0xAdiyat Any chance? Or did you abandon development of this app?

**Comment by 0xAdiyat** [comment]
> @0xAdiyat Any chance? Or did you abandon development of this app?

Hey @IzzySoft, how are you doing? My apologies, it slipped my mind. I'm currently swamped with various projects, and unfortunately, I don't foresee having much time to contribute to the app, at least for now. I appreciate your understanding and thanks for the reminder! <3

**Comment by IzzySoft** [comment]
And I very much appreciate your response, @0xAdiyat! And also fully understand "being swamped" (I perfectly know that situation from my own experience).

May I ask which of the possible options you'd prefer here?

* you sign the latest APK with a proper release key and make the resulting file available, so I replace [the one in my repo](https://apt.izzysoft.de/packages/com.anon007.todo_wishflow/)
* I remove your app from my repo now, and you ping me should you have a properly signed APK ready (so no action needed from your side unless you finally found time for and decided to work on this project again)

**Comment by 0xAdiyat** [comment]
> And I very much appreciate your response, @0xAdiyat! And also fully understand "being swamped" (I perfectly know that situation from my own experience).
> 
> May I ask which of the possible options you'd prefer here?
> 
> * you sign the latest APK with a proper release key and make the resulting file available, so I replace [the one in my repo](https://apt.izzysoft.de/packages/com.anon007.todo_wishflow/)
> * I remove your app from my repo now, and you ping me should you have a properly signed APK ready (so no action needed from your side unless you finally found time for and decided to work on this project again)

Haha true and yes definitely the 2nd option is suiting me the most rn.

**Comment by IzzySoft** [comment]
OK, then we take that. And as offered: be welcome to reach out to me should you want the app back in one day!
